name: CI

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, no-aws-creds-runner]

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
          
      - name: aws sts
        run: aws sts get-caller-identity
        shell: bash 
        
      - name: digger run
        uses: diggerhq/digger@no-aws-creds
        with:
          setup-aws: false
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
